language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"

before_install:
  - npm install
  - cd packages/fx-schema-form-core
  - npm install
  - cd ../fx-schema-form-react
  - npm install
  - cd ../../

after_script:
  - echo "ok"

notifications:
  email:
    recipients:
      - nick121212@126.com
    on_success: change
    on_failure: always