language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"

before_install:
  - cd packages/fx-schema-form-core
  - npm install
  - cd ../fx-schema-form-react
  - npm install

after_script:
  - echo "ok"
